apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  workspaces:
    - description: >
        This workspace is shared among all the pipeline tasks to read/write
        common resources
      name: source
  tasks:
    - name: build-image1
      runAfter:
        - build-oci-chart
      timeout: 30m
      retries: 3
      taskRef:
        kind: ClusterTask
        name: build-image
      workspaces:
        - name: source
          workspace: source
      params:
        - name: container-image
          value: 192.168.17.28:18081/devops/go-demo1
        - name: container-image-tag
          value: v1
        - name: dockerfile
          value: ./Dockerfile
        - name: labels
          value: []
        - name: context
          value: .
        - name: push-extra-args
          value: --storage-driver=vfs --tls-verify=false
        - name: build-extra-args
          value: --storage-driver=vfs --tls-verify=false
        - name: format
          value: docker
    - name: build-oci-chart
      timeout: 30m
      retries: 3
      taskRef:
        kind: ClusterTask
        name: build-oci-chart
      workspaces:
        - name: source
          workspace: source
      params:
        - name: dir
          value: ./chart
        - name: address
          value: 192.168.17.28:18081/devops/go-demo-chart
        - name: v1
          value: go-demo-chart
        - name: labels
          value: []
        - name: registry-login-options
          value: --insecure
        - name: chart-push-options
          value: --insecure
